### ISSUE TITLE
Motivation output

### ISSUE THREAD

**Issue by ghost** [anno4j/anno4j#119]
The following implementations:

```
Motivation bookmarking = MotivationFactory.getBookmarking(anno4j);
 annotation.addMotivation( bookmarking); 
```

OR

```
  HashSet<Motivation> motivations = new HashSet<Motivation>();
  Motivation bookmarking = MotivationFactory.getBookmarking(anno4j);
  motivations.add(bookmarking);
  annotation.setMotivatedBy(motivations);
```

shows a duplicate value to rdf:type, as following:

```
<rdf:Description rdf:about="urn:anno4j:7991c4d5-024c-4215-b26a-487bb9ca21a5">
    <rdf:type rdf:resource="http://www.w3.org/ns/oa#Motivation"/>
    <rdf:type rdf:resource="http://www.w3.org/ns/oa#Motivation"/>
    <rdf:type rdf:resource="https://github.com/anno4j/ns#Resource"/>
</rdf:Description>
```

and skip the value:  http://www.w3.org/ns/oa#bookmarking

The class AnnotationTest also needs to be update. The method testMotivation() doesn't verify this consistency.

**Comment by berndl** [comment]
Hi @silviodc ,
thanks for committing the issue!

Unfortunately we are kinda busy at the moment, but we will look into your issues in the near future!

**Comment by Weissger** [comment]
Hi @silviodc,
this was already fixed in the develop branch of Anno4j. It will be released to the master branch soon.

For now you could change to the most up-to-date snapshot version "2.3.1-SNAPSHOT" to solve the issue.
