### ISSUE TITLE
Problems to insert setResourceAsString in a external graph

### ISSUE THREAD

**Issue by ghost** [anno4j/anno4j#120]
I'm using the develop branch and trying to store the anno4j into Virtuoso, using a specific graph. However, the specification of the method: 
`@Override
    public void setResource(Resource resource) throws MalformedQueryException, RepositoryException, UpdateExecutionException {
        String query = "DELETE {?s ?p ?old}" +
                    " INSERT {?s ?p ?new}" +
                    " WHERE {" +
                    " BIND(<"+this.getResourceAsString()+"> as ?old)" +
                    " BIND(<"+resource+"> as ?new)" + .....`

doesn't allow the use of a specific graph. All the data instances are computed in the default graph.

I have tested : `Annotation annotation = anno4j.createObject(Annotation.class,uri);`
`SpecificResource specificResource = anno4j.createObject(SpecificResource.class,uri);`
`TextPositionSelector textPositionSelector = anno4j.createObject(TextPositionSelector.class,uri);`
`SpecificResource source = anno4j.createObject(SpecificResource.class,uri);`
`TextualBody body = anno4j.createObject(TextualBody.class,uri);`

All these calls worked well ! I only have problems with  `body.setResourceAsString("doc1234");`

**Comment by Weissger** [comment]
Hi @silviodc,

thanks for reporting the issue.

I fixed the query on develop and it will be released in a SNAPSHOT soon.
