### ISSUE TITLE
Using prefix in QueryService's addCriteria

### ISSUE THREAD

**Issue by fischmat** [anno4j/anno4j#126]
The Anno4j QueryService allows definition of prefixes. On the other hand it is not possible to use previously defined prefixes in the value argument of e.g. `QueryService.addCriteria(String ldpath, String value)`.
So for example the following query would not return a previously persisted resource `http://example.org/myAnno`:

`qs.addPrefix("ex", "http://example.org/")`
`.addCriteria(".", "ex:myAnno")`
`.execute(Annotation.class);`

Resolution of resources in prefix notation would make querying more concise.

**Comment by berndl** [comment]
Hi @fischmat !

I have pushed a (preliminary, as I am sure there would be a more thorough solution down there in Marmotta :)) fix to the develop branch!
https://github.com/anno4j/anno4j/commit/e6e8f57f079446b98dcc816f467e2bc681fcfb0b

Please check if your things work with that solution!

**Comment by fischmat** [comment]
Now it works :) 
I think this way querying is more straightforward.
