### ISSUE TITLE
Add createTransaction(URI context) to Anno4j class

### ISSUE THREAD

**Issue by berndl** [anno4j/anno4j#141]
The Anno4j object should have another method to create a Transaction, also supporting a URI as context for the operations done in that Transaction.

Up to now Users had to do that by hand after creating the Transaction, which is a kinda strange behaviour. It also sometimes induces wrong/unexpected behaviour.

**Comment by fischmat** [comment]
I added the method to the Anno4j class in branch `hotfix/transaction-contexts`.
It creates a transaction and sets the contexts of the internal `ObjectConnection` using the `setAllContexts()` method.
