### ISSUE TITLE
Getting AbstractMethodError

### ISSUE THREAD

**Issue by ghost** [anno4j/anno4j#144]
Hi Everyone,

I'm trying to build a single jar which contains` myProject` and all `anno4j dependencies`.
To do so, i created a module inside the `anno4j-parent` and i included `myProject` there.

So, the structure is like that:

```
----anno4j-parent
           ----anno4-core
           ---- others...
           ---- myProject
```

Now to include all jar i'm using the `maven-shade-plugin:3.0.0:shade`. 

At beginning everything works on eclipse, see the maven output hereafter:

```
[INFO] Anno4j Parent ...................................... SUCCESS [  3.711 s]
[INFO] Anno4j AliBaba (forked) ............................ SUCCESS [  0.024 s]
[INFO] Anno4j Alibaba Object Composition (forked) ......... SUCCESS [ 17.839 s]
[INFO] Anno4j Alibaba Blob Store (forked) ................. SUCCESS [  5.337 s]
[INFO] Anno4j Alibaba Object Repository (forked) .......... SUCCESS [ 11.004 s]
[INFO] Anno4j Core ........................................ SUCCESS [ 15.057 s]
[INFO] Anno4j Ontologies .................................. SUCCESS [  0.036 s]
[INFO] Anno4j MICO Ontology ............................... SUCCESS [  5.875 s]
[INFO] Anno4j Recommendation .............................. SUCCESS [  4.670 s]
[INFO] Anno4j Extensions .................................. SUCCESS [  0.030 s]
[INFO] Anno4j SPARQLMM Extension .......................... SUCCESS [  0.078 s]
[INFO] MAISA - Maintenance of semantic annotations ........ SUCCESS [ 32.295 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:36 min
```

The problem is when i use it in the command line: `java -jar myProject.jar`
I'm receving the following error when i execute the Main.class
```
Exception in thread "main" java.lang.AbstractMethodError: object.proxies._1acbd9a953b._EntityProxy8b0403296799bdd.addTarget(Lcom/github/anno4j/model/Target;)V
	at myProject.main.Main.main(Main.java:17)
```

It is strange because  **in eclipse terminal everything works**, but in the command line i get this error.
Before i was including all separeted jars in my project to share it with others.

However it is time consuming and i got some issues of dependencies, see this issue #121 

So the example i mentioned before can be accessed in my GitHub repository: [my Anno4j Project](https://github.com/silviodc/anno4j/tree/develop) 
Do you guys have some ideia why is it happening?

Best Regards,
Silvio

**Comment by berndl** [comment]
Hi @silviodc ,

you found a pretty ugly one there :)
Thomas and myself tried to look into it for a while, but we couldn't find a solution yet.
The objects created in your own project do not receive the correct behaviour of the Anno4j/Alibaba objects that they should receive.

We will ping again as soon as we find something.

Best,
Manu

**Comment by ghost** [comment]
Hi @berndl 
Thanks so much for your answer!
After to try many things last week, i finally solved the problem :D 

I added the following lines in my `pom.xml`
```
<transformer implementation="org.apache.maven.plugins.shade.resource.PluginXmlResourceTransformer" />
<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
		<mainClass>myProject.main.Main</mainClass>
</transformer>
```
Now everything is building and executing correctly :+1:  

Take a look at my repository [my Anno4j project](https://github.com/silviodc/anno4j/tree/develop)

Best,
Silvio

**Comment by berndl** [comment]
Hi @silviodc ,

even better that you found the solution and did not have to wait for us :) Sorry that we could not support a solution!
I tested it quickly and it worked like a charm.

Thanks for finding and solving the issue, best,
Manu
