### ISSUE TITLE
Change ObjectParser to be able to read a generic class/multiple classes

### ISSUE THREAD

**Issue by berndl** [anno4j/anno4j#155]
The current implementation of the ObjectParser is restricted to the Annotation class.
It should be feasible to implement a generic one, which could also parse different objects as well.

**Comment by fischmat** [comment]
The `ObjectParser` new features a new generic `parse(Class<?>, String, URL, RDFFormat, boolean)` method that can be used to parse objects of any type. The old implementation still exists and was marked deprecated (see pull request #159). We need to remember the remove it some time in the future...
