### ISSUE TITLE
transform to web annotation model

### ISSUE THREAD

**Issue by schlegel** [anno4j/anno4j#3]

**Comment by berndl** [comment]
Current OADM approach is not far from the standard of the Web Annotation Working Group.

(Possible) Missing features:
- Support Fragment URI at target resource level?
- Allow simple text bodies?
- Multiplicity (see http://www.w3.org/TR/2014/WD-annotation-model-20141211/#multiplicity)

**Comment by schlegel** [comment]
we should look into the web annoations service api, maybe we can provide an integrated services in anno4j
