### ISSUE TITLE
Delete Annotations

### ISSUE THREAD

**Issue by schlegel** [anno4j/anno4j#37]

**Comment by berndl** [comment]
Also support other CRUD functionality, update, etc..

**Comment by papadako** [comment]
Do you have any specific plan about delete and update?

**Comment by papadako** [comment]
Hope https://github.com/anno4j/anno4j/pull/51 is in the right direction.

**Comment by AEisenkolb** [comment]
Hey @papadako and @schlegel,

I implemented a delete mechanism see fdb6a089c920c3b55f263ce80b2976dc728eae05

best regards
