### ISSUE TITLE
Create Annotation instance using a json-ld serialization

### ISSUE THREAD

**Issue by papadako** [anno4j/anno4j#43]
I guess it would be rather helpful to create Annotation instances by passing json-ld serializations

**Comment by schlegel** [comment]
@berndl is currently working on this issue

**Comment by berndl** [comment]
The current Snapshot introduces an ObjectParser, which allows to read different serializations of annotations, e.g. JSONLD, Turtle, etc.

You need to create an instance of the ObjectParser, which then takes your input as String, a base URI and the format that you want to parse (which is an instance of RDFFormat). Keep in mind, that the file needs all its correct contexts and namespaces to work. Also, every RDF node needs a type or needs to be a literal only. The parse function then returns a list of the Annotation objects that have been created in the parse process.

Examples can also be seen in the ObjectParserTest, found in the anno4j-core project.

**Comment by papadako** [comment]
I do not think that it works as expected though. Printing the triples of created annotations only return http://aURI http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.w3.org/ns/oa#Annotation .

**Comment by berndl** [comment]
Would you show me what input you used? And which printing method?

**Comment by papadako** [comment]
There was an error in the json-ld context that I used. I guess https://raw.githubusercontent.com/w3c/web-annotation/gh-pages/jsonld/anno.jsonld is what we should be using. Right?

**Comment by berndl** [comment]
Yup, that one should work for JSON-LD.

**Comment by papadako** [comment]
How can the ObjectParser be aware of the available body implementations, without having to use inner classes like in the ObjectParserTest?

**Comment by berndl** [comment]
You can create your own classes (just follow the example of the inner classes that you already found) somewhere else.
Make sure to annotate the interface, its getters and setters accordingly, and that (if it is a new class that the OA-context does not know) it is added to your JSON-LD context.
The inner classes were just used for testing purposes.

**Comment by papadako** [comment]
Thank you for your help berndl. 

Unfortunately I am not able to make it work. I try to create a simple annotation with body the TextAreaBody.java that you have in anno4j-ontologies/ontologies-mico/src/main/java/eu/mico/platform/anno4j/model/impl/body. So I use the following annotation

``` java
String annotation = "{\n"
                + "  \"@context\":\"https://raw.githubusercontent.com/w3c/web-annotation/gh-pages/jsonld/anno.jsonld\",\n"
                + " \"@type\":\"oa:Annotation\" , \n"
                + " \"body\": { \n"
                + " \"@type\":\"dctypes:Text\", \n"
                + " \"value\":\"This should be the content\", \n"
                + " \"format\":\"text/plain\" \n"
                + " }, \n"
                + " \"target\": { \n"
                + " \"@id\": \"http://dbpedia.org/page/Yellowfin_tuna\" \n"
                + " }\n"
                + "}";
```

ObjectParser creates the annotations, but toString throws the  exception I enclose at the end. Getting the NTtriples shows that there are no triples related to body and target.

```
Exception in thread "main" java.lang.IllegalStateException: Connection has been closed
    at org.openrdf.sail.helpers.SailConnectionBase.verifyIsOpen(SailConnectionBase.java:159)
    at org.openrdf.sail.helpers.SailConnectionBase.getStatements(SailConnectionBase.java:340)
    at org.openrdf.repository.sail.SailRepositoryConnection.getStatements(SailRepositoryConnection.java:215)
    at org.openrdf.repository.base.RepositoryConnectionWrapper.getStatements(RepositoryConnectionWrapper.java:322)
    at org.openrdf.repository.contextaware.ContextAwareConnection.getStatements(ContextAwareConnection.java:547)
    at org.openrdf.repository.object.advisers.helpers.RemotePropertySet.getStatements(RemotePropertySet.java:432)
    at org.openrdf.repository.object.advisers.helpers.RemotePropertySet.getValues(RemotePropertySet.java:436)
    at org.openrdf.repository.object.advisers.helpers.RemotePropertySet.getObjects(RemotePropertySet.java:459)
    at org.openrdf.repository.object.advisers.helpers.CachedPropertySet.getObjects(CachedPropertySet.java:276)
    at org.openrdf.repository.object.advisers.helpers.CachedPropertySet.getObjectIterator(CachedPropertySet.java:294)
    at org.openrdf.repository.object.advisers.helpers.RemotePropertySet.getSingle(RemotePropertySet.java:173)
    at org.openrdf.repository.object.advisers.helpers.CachedPropertySet.getSingle(CachedPropertySet.java:176)
    at org.openrdf.repository.object.advisers.FieldBehaviour.getFieldValue(FieldBehaviour.java:191)
    at org.openrdf.repository.object.advisers.FieldBehaviour.intercept(FieldBehaviour.java:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.openrdf.repository.object.composition.helpers.InvocationMessageContext.proceed(InvocationMessageContext.java:245)
    at org.openrdf.repository.object.behaviours.RDFObjectImpl.toString(RDFObjectImpl.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.openrdf.repository.object.composition.helpers.InvocationMessageContext.proceed(InvocationMessageContext.java:245)
    at object.proxies._1acbd9a953b._EntityProxy98b7ac660a.toString(_EntityProxy98b7ac660a.java)
```

**Comment by berndl** [comment]
There is actually a problem, if you try to use annotated classes of another project, as the dependency of the anno4j-ontologies-mico is not included in the core project, so the parser cannot associate the correct object to the given Iri.

I altered the TextAreaBody to your needs, and also supported a test with your given JSON-LD (in the anno4j-ontologies-mico project!), so you can see how to use it. There you can also see, how to use the annotation, retrieve its body etc. Both should be supported in the current version.

Please test it again and let me know, if there are any further problems.

**Comment by berndl** [comment]
The test is called TextAreaBodyTest, respectively :)

**Comment by papadako** [comment]
Hi again berndl. Thanks for the help, I really appreciate it.

Unfortunately I cannot make it work. Just a clarification, I was using my own body class implementation in my project, not the TextAreaBodyTest from another maven project. The testcase that you have uploaded though works as expected.

I am not sure what is wrong. I have created my own namespace and tried to create another body. Initially I got a different exception, because I had no default constructor. After adding the default constructor I got the same exception as the one I previously posted. So I guess that there is a correct association to the body object and something else is wrong. 

I added the current code below. The isValid is a method that returns if the value is valid, inherited from the abstract class BodyWithValidity which extends Body.

``` java
package annotations.annotation.body;
import com.github.anno4j.model.namespaces.RDF;
import annotations.annotation.namespaces.POLYTRAITS;
import org.openrdf.annotations.Iri;

/**
 * A measurement of the longest dimension of a body, typically between two
 * distinct ends of the body.
 */
@Iri(POLYTRAITS.CMO_0000013)
public class CMO_0000013Body extends BodyWithValidity {

    /**
     * Value of Morphometric characteristic
     */
    @Iri(RDF.VALUE)
    private String value = "";

    // Every defined body needs a default constructor
    public CMO_0000013Body() {
    }

    public CMO_0000013Body(String value) {
        this.value = value;
    }

    /**
     * Check that the annotation has a valid value
     *
     * @return
     */
    public boolean isValid() {
        switch (value) {
            case POLYTRAITS.CMO_0000013_BS_1:
            case POLYTRAITS.CMO_0000013_BS_2:
            case POLYTRAITS.CMO_0000013_BS_3:
            case POLYTRAITS.CMO_0000013_BS_4:
            case POLYTRAITS.CMO_0000013_BS_5:
            case POLYTRAITS.CMO_0000013_BS_6:
            case POLYTRAITS.CMO_0000013_BS_7:
                return true;
            default:
                return false;
        }
    }

    /**
     * Sets new The actual textual content..
     *
     * @param value New value of The actual textual content..
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets The actual textual content..
     *
     * @return Value of The actual textual content..
     */
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return "CMO_0000013Body{"
                + "value='" + value + '\''
                + "}";
    }
}
```

Exception

```
2015-10-08 23:45:47 DEBUG [main] org.openrdf.sail.memory.MemoryStore [MemoryStore.java:334] MemoryStore initialized
Exception in thread "main" java.lang.IllegalStateException: Connection has been closed
    at org.openrdf.sail.helpers.SailConnectionBase.verifyIsOpen(SailConnectionBase.java:159)
    at org.openrdf.sail.helpers.SailConnectionBase.getStatements(SailConnectionBase.java:340)
    at org.openrdf.repository.sail.SailRepositoryConnection.getStatements(SailRepositoryConnection.java:215)
    at org.openrdf.repository.base.RepositoryConnectionWrapper.getStatements(RepositoryConnectionWrapper.java:322)
    at org.openrdf.repository.contextaware.ContextAwareConnection.getStatements(ContextAwareConnection.java:547)
    at org.openrdf.repository.object.advisers.helpers.RemotePropertySet.getStatements(RemotePropertySet.java:432)
    at org.openrdf.repository.object.advisers.helpers.RemotePropertySet.getValues(RemotePropertySet.java:436)
    at org.openrdf.repository.object.advisers.helpers.RemotePropertySet.getObjects(RemotePropertySet.java:459)
    at org.openrdf.repository.object.advisers.helpers.CachedPropertySet.getObjects(CachedPropertySet.java:276)
    at org.openrdf.repository.object.advisers.helpers.CachedPropertySet.getObjectIterator(CachedPropertySet.java:294)
    at org.openrdf.repository.object.advisers.helpers.RemotePropertySet.getSingle(RemotePropertySet.java:173)
    at org.openrdf.repository.object.advisers.helpers.CachedPropertySet.getSingle(CachedPropertySet.java:176)
    at org.openrdf.repository.object.advisers.FieldBehaviour.getFieldValue(FieldBehaviour.java:191)
    at org.openrdf.repository.object.advisers.FieldBehaviour.intercept(FieldBehaviour.java:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.openrdf.repository.object.composition.helpers.InvocationMessageContext.proceed(InvocationMessageContext.java:245)
    at object.proxies._1acbd9a953b._EntityProxy98b7ac660a.getBody(_EntityProxy98b7ac660a.java)
    at annotations.annotation.body.JSONLD.main(JSONLD.java:260)
```

**Comment by berndl** [comment]
Hm, the exception seems like you have lost the SailRepository that contains the (temporary) annotations that you have parsed with the ObjectParser. Those are at that time NOT persisted in your Anno4j Instance. You can only use those annotations as long as the ObjectParser exists.

Did you call the .shutdown() method of the ObjectParser, before trying to use the annotation objects? Trying to reproduce that situation gives me a similar exception.

If you want to persist those annotations for further utilisation, you should persist them. That would look something like this:

```
Annotation anno = ...
Anno4j anno4j = Anno4j.getInstance();
anno4j.createPersistenceService().persistAnnotation(anno);
```

From there, they then are query- and usable.

I hope this fixes your problem!

**Comment by berndl** [comment]
P.S.: Your body looks fine, with the correct context in the JSON-LD, it should work.

**Comment by papadako** [comment]
Thank you for your time berndl. That .shutdown() was the problem.
Regards Panagiotis

**Comment by papadako** [comment]
Unfortunately, I am stuck in another issue. The original JSON-LD annotations that I read have no id, and as a result ResourceObject creates blank nodes. So I am trying to create my own URIs and change the id of the annotation from a blank node to an automatically generated id. But unfortunately I always get a blank node for the annotation. The annotations list in for, holds the annotations read by the ObjectParser.

``` java
            for (Annotation anno : annotations) {
                // Add new resources for annotation id
                // Create a URI for the annotation
                UUID idAnno = UUID.randomUUID();
                // Use the UUID
                String annoURI = url.toString() + idAnno.toString();
                // Create the resource
                ResourceObject annoResource = new ResourceObject(annoURI);
                try {
                    //anno.getObjectConnection().removeDesignation(anno, Annotation.class);
                    //anno.getObjectConnection().addObject(annoURI, annoResource);
                    anno.setResource(annoResource.getResource());
                    anno.getObjectConnection().addObject(anno);
                } catch (RepositoryException ex) {
                    Logger.getLogger(JSONLD.class.getName()).log(Level.SEVERE, null, ex);
                }

                System.out.println(anno.toString());
                System.out.println(anno.getResource());
                System.out.println(anno.getResourceAsString());

                //Do the same for the body....

                // Now modify the annotation to include serialization information
                insertProvenanceAndSerializationInformation(anno);
            }
```

**Comment by berndl** [comment]
Are you still using JSON-LD examples like the one above?

```
String annotation = "{\n"
                + "  \"@context\":\"https://raw.githubusercontent.com/w3c/web-annotation/gh-pages/jsonld/anno.jsonld\",\n"
                + " \"@type\":\"oa:Annotation\" , \n"
                + " \"body\": { \n"
                + " \"@type\":\"dctypes:Text\", \n"
                + " \"value\":\"This should be the content\", \n"
                + " \"format\":\"text/plain\" \n"
                + " }, \n"
                + " \"target\": { \n"
                + " \"@id\": \"http://dbpedia.org/page/Yellowfin_tuna\" \n"
                + " }\n"
                + "}";
```

Those are missing an "@id" tag for the annotation. If you add that at top level, the annotation should have an ID. So it should look something like this:

```
String annotation = "{\n"
                + "  \"@context\":\"https://raw.githubusercontent.com/w3c/web-annotation/gh-pages/jsonld/anno.jsonld\",\n"
                + " \"@id\": \"http://example.org/anno1\" , \n"
                + " \"@type\":\"oa:Annotation\" , \n"
                + " \"body\": { \n"
                + " \"@type\":\"dctypes:Text\", \n"
                + " \"value\":\"This should be the content\", \n"
                + " \"format\":\"text/plain\" \n"
                + " }, \n"
                + " \"target\": { \n"
                + " \"@id\": \"http://dbpedia.org/page/Yellowfin_tuna\" \n"
                + " }\n"
                + "}";
```

Also if you want to persist those annotations, please use an instance of Anno4j, like this:

```
Annotation anno = ...
Anno4j anno4j = Anno4j.getInstance();
anno4j.createPersistenceService().persistAnnotation(anno);
```

**Comment by papadako** [comment]
Hi berndl. I am trying to create a REST service, where annotations are given by the client. Ids for this annotation should be given by the server, who is responsible for persisting them using Anno4j in a virtuoso triplestore. The problem is that by using ObjectParser to parse the client-side annotation, all resources get a blank node as an id, which afterwards I am unable to update using the correct ids generated by the server. The only way I found is to create new Annotation and Body instances using the information given by the client, as parsed by the ObjectParser and add my own ids and then persist them. Is there a better way?

P.S.
What is the best way to remove a resource from an ObjectConnection? According to https://github.com/anno4j/anno4j/tree/master/anno4j-alibaba/object-repository I have to set to null all its fields and call removeDesignation(annotation, Annotation.class) right? And I guess the same for the body or any other resource. By the way is there a method to clear the ObjectConnection without shutting it down?

Thank you
Best regards
Panagiotis

**Comment by schlegel** [comment]
Hi, 
maybe a custom ID generator is the right way for you? From our documentation: 
"For RDF creation, Anno4j need a central instance for generating unique identifiers. The ID generator needs to implement the com.github.anno4j.persistence.IDGenerator interface. To activate your ID generator, just create a corresponding object and set it in the Anno4j instance."
    anno4j.setIdGenerator(new MyIDGenerator());

You can see an example implementation in com.github.anno4j.persistence.impl.IDGeneratorAnno4jURN, which is the default IdGenerator. All new Resources will get an ID from the provided generator.

If this is not the solution i would suggest the following (Note. Use anno4j to persist your object, not the underlying aliababa implementation): 

```
            for (Annotation anno : annotations) {
                                anno.setResource(new MemValueFactory().createURI("urn:yourUrlPrefix:" +UUID.randomUUID()));
                                Anno4j.getInstance().createPersistenceService().persistAnnotation(anno);

            System.out.println(anno.toString());
            System.out.println(anno.getResource());
            System.out.println(anno.getResourceAsString());

            //Do the same for the body....

            // Now modify the annotation to include serialization information
            insertProvenanceAndSerializationInformation(anno);
        }
```

**Comment by papadako** [comment]
I am not sure if what you propose is what I would like to do. I guess defining a new ID generator will affect only those annotations that are persisted in the triple store, and will generate ids for those resources that have no id.

What I am doing though is that I use the ObjectParser to read json-ld annotations. The basic point is that even if an annotation has its own ids for the annotation itself or body, I would like to create my own ones.
So after reading a json-ld annotation, I would like to create a new URI, set it to the annotation just read by the ObjectParser, and then persist it. But setResource(newURI) does not work (the annotation instance holds the original blank node and not the new URI, if I call getResource(), getResourceAsString returns the though the correct id).  What I am currently doing is to create a new Annotation, populate it with the information that is held by the Annotation instance created by ObjectParser, set a new Resource as its resource and then persist it.

Hope now it is more clear.

**Comment by berndl** [comment]
Hey @papadako ,

I am trying to reproduce your issue, so please help me if i get it completely right:
- Clients are sending annotation information to your server (as a JSONLD string? Or is the String generated at your server?)
- The server uses the ObjectParser to generate an Annotation object from the client information
- For that Annotation object you would like to change the ID, right?
- Then you persist it to Anno4j

Maybe I can build up a test an help then.

**Comment by papadako** [comment]
Hi @berndl.
Yep, this is the case

**Comment by berndl** [comment]
Hey @papadako ,

there is kind of bad and kind of good news ;)
The bad things first: there is an issue about the IDs of annotation objects and those annotations that are persisted to a given repository. In this case, this is already the repository that is used for the parsed annotations.
To fix this might take some time, and with our current efforts in other duties, we cannot promise to fix this at hand.

However, and this is the "kinda good" news: we are working on an improved version of Anno4j, which can be found at the development-v2 branch. In that version i wrote a test and tried exactly what you are planning to do, and it works just fine.
So you could migrate to version 2, which has improvements in various directions, but it is not super stable yet. Nevertheless, we hope to fully publish it in the near future.

Version 2 breaks the current version 1 API, but we can surely support you with the migration process, if you so desire!

**Comment by papadako** [comment]
Ok, I will try to make the transition.

By the way, it seems that the development-v2 branch does not include a number of commits like
aa54be13, d9d81ba54 that are in develop.

**Comment by schlegel** [comment]
I integrated the aa54be1 manually when we moved to version 2. d9d81ba can be omitted because the new version don't uses constructors anymore. Thats a major change in version 2, because instances are not longer created manually with "new", but rather directly instantiated by Anno4j. Unfortunately we haven't updated the documentation yet, but the unit tests are already adapted. Maybe you can take a first look there? The hole transition was necessary for example to allow multiple types for a resource.
