### ISSUE TITLE
Reuse of blank nodes

### ISSUE THREAD

**Issue by papadako** [anno4j/anno4j#45]
For example, instead of creating a new blank node for provenance agents per each annotation, when all annotations are serialized by the same software agent/the same person, etc.

**Comment by schlegel** [comment]
still important? can you give detailed information? you can use the same agent object for multiple annotaitons. Or you can create new objects with the same URI.

**Comment by papadako** [comment]
No it is not important. The idea was before generating a new blank node to check if another one could match this one.
