### ISSUE TITLE
[Development guidelines] 

### ISSUE THREAD

**Issue by papadako** [anno4j/anno4j#52]
Is it possible to add some development guidelines (e.g. how to build, test, etc)? 

I am new to the world of maven and up to now whenever I make a change to anno4j-core, I run "mvn package" at the anno4j-parent to build the corresponding jar I want to test. I guess this is not the correct process.

**Comment by schlegel** [comment]
Thats a good idea. We will integrate a developer guide in the readme of version 2.0.0. V2 will change a lot and makes the development a bit easier.

**Comment by schlegel** [comment]
included in v2
