### ISSUE TITLE
[ResourceObject] getNTriples is rather slow

### ISSUE THREAD

**Issue by papadako** [anno4j/anno4j#54]
In my system it takes 6664 ms to return the results. Is this an expected behaviour?

**Comment by schlegel** [comment]
So far the getNTriples was just a way to show the underlying triples (mostly debug purpose). Can you explain your use-case? Maybe there is another way or we can tune the getNtriples

**Comment by papadako** [comment]
Well, I am using the N-triples serialization to transform it to JSON-LD. I guess either the ResourceObject class or Annotation should have its own serialization methods for JSON-LD or N-triples correspondingly.

**Comment by berndl** [comment]
Hey @papadako ,
we are also interested in a way to put out our annotations in different serialisation formats, but couldn't find the time yet to implement it.
The Sesame Rio API (which we also use to parse the annotations) does also support possibilities to produce that output.  I hope to be able to look into that next week, maybe I can support a solution for you then.

**Comment by papadako** [comment]
Thank you @berndl that would be nice.
I guess I should probably try and implement it by my own but I am not yet accustomed to the anno4j code base and the whole building process needs.

**Comment by berndl** [comment]
Hello @papadako ,
I implemented the output for ResourceObjects with the "getTriples" method, that should allow to print every object that is used in our Anno4j context.
You have to support a RDFFormat (just as we did with the ObjectParser) in order to generate your desired serialisation.

Tests for the method are rather shallow yet, but at first sight, it worked quite well. I will support further testing soon though.

**Comment by papadako** [comment]
Hi @berndl 
getTriples still seem a bit slow. Now it takes 3663ms. Could this be related to the initialization of the SAIL and object repositories? Maybe I also have to disable all debugging from the jars.

Edit: Disabling debugging does not help.
So can we reopen this?

**Comment by papadako** [comment]
V2 has fixed this.
Thank you.
