### ISSUE TITLE
Tests in Recommendation Module

### ISSUE THREAD

**Issue by schlegel** [anno4j/anno4j#57]
@berndl 

java.lang.AssertionError: expected:<0> but was:<1>
[INFO]  at org.junit.Assert.fail(Assert.java:88)
[INFO]  at org.junit.Assert.failNotEquals(Assert.java:834)
[INFO]  at org.junit.Assert.assertEquals(Assert.java:645)
[INFO]  at org.junit.Assert.assertEquals(Assert.java:631)
[INFO]  at com.github.anno4j.recommendation.model.SimilarityStatementTest.testSimilarityStatement(SimilarityStatementTest.java:56)
[INFO] 

Create a new Memory Store in each @Before method to always have a cleared store

**Comment by berndl** [comment]
Should be fixed, both in v1 and v2.
