### ISSUE TITLE
Support User in creating Provenance Information at Annotation Level

### ISSUE THREAD

**Issue by berndl** [anno4j/anno4j#59]
Like for the selectors, we should help or guide the user to create provenance information (when it is possible) at some levels.

For example timestamps for the "annotatedAt" field should follow a given structure.  At the current phase, this is just a String, which then can be faulty, and not applicable by WADM standards etc.

Examples could be "setAnnotatedAtToNow", "setAnnotatedAtToTime(Time time)".

**Comment by schlegel** [comment]
done in v2
