### ISSUE TITLE
Clean up extractors and MMM vocabulary

### ISSUE THREAD

**Issue by berndl** [anno4j/anno4j#60]
In both the list of extractors and the MMM vocabulary, there are old items that are either deprecated or not used at all anymore.

**Comment by AEisenkolb** [comment]
still an issue?

**Comment by berndl** [comment]
We streamlined all the MICO related resources in the hackathon in Ilmenau in february. We should stick to only those.

They are to be found in the mmm-anno4j module of the MICO-platform.
