### ISSUE TITLE
Sesame 2.8 upgrade

### ISSUE THREAD

**Issue by papadako** [anno4j/anno4j#66]

**Comment by AEisenkolb** [comment]
Hey @papadako,

I just updated our sesame dependencies to version 2.8.8 (see commit 4f1766c22ff0a860141e1d57540388f4ba1b3878)

**Comment by papadako** [comment]
Hi @AEisenkolb 
It seems that anno4j-core is still dependent to sesame 2.7.12. Probably there is some other dependency?

By the way since the  jsonld-java-sesame dependency has been included in the sesame project in 2.8 there is no need for the 0.5.1 dependency in the pom.xml. Consequently the jsonld-java dependency could also be updated to a more recent version, like the 0.7.
P.S.
Do you have any plans for a 2.0.1 release with the updated dependencies?

Thank you and best regards

**Comment by AEisenkolb** [comment]
Hi @papadako,

I inspected the dependency graph of anno4j-core, but I could not found any sesame 2.7.12 dependency. Can you give me a hint where to find?

I also updated the jsonld-java dependency to the latest version (0.7.0), hope that's fine for you?

We can release 2.0.1 with the new updated dependencies as soon as you are fine with the current v2-development state.

Best regards

**Comment by papadako** [comment]
Hi @AEisenkolb.

I think that it comes from the ldpath-backend-sesame which is still in version 3.3, while the rest ldpath related jars are in 3.4 SNAPSHOT.

I hope that the 2 commits in the develop branch will also be merged in 2.0.1.

Thank you for your support
Panagiotis

**Comment by papadako** [comment]
Also it seems that in object-repository and object-composition of anno4j-alibaba  all openrdf dependencies need a <version>2.8.8</version>.
Maybe something is wrong with my repo?

**Comment by AEisenkolb** [comment]
Hi @papadako,

I updated the ldpath-backend-sesame dependency to 3.4-SNAPSHOT and the jsonld-java dependency to 0.7 (see 07e0aff2ac6186daf220989287c57aae613695a3). 

Which 2 commits do you mean to be merged in 2.0.1?

As mentioned above, I updated the sesame dependencies of the anno4j-alibaba module to 2.8.8  (4f1766c). Is that not what you requested initially?

**Comment by papadako** [comment]
Hi again @AEisenkolb 

I made a clean build of the whole anno4j and I think that everything is ok.
About the  two commits I mean the commits in the develop branch. Basically I am interested in
7ba370f 

Thanks again
Panagiotis

**Comment by papadako** [comment]
Hi @AEisenkolb 

Can you please check the pom.xml of the object-repository?
There is an explicit versioning to the sesame-repository-api to 2.8.3, which I guess is not needed.
Also do you plan to merge your commits in v2-develop to the develop branch?

Thank you

**Comment by papadako** [comment]
Attached the diff

```
diff --git a/anno4j-alibaba/object-repository/pom.xml b/anno4j-alibaba/object-repository/pom.xml
index 069e941..ff926ab 100644
--- a/anno4j-alibaba/object-repository/pom.xml
+++ b/anno4j-alibaba/object-repository/pom.xml
@@ -34,7 +34,6 @@ The Object Repository maps Java objects to and from RDF resources and OWL classe
         <dependency>
             <groupId>org.openrdf.sesame</groupId>
             <artifactId>sesame-repository-api</artifactId>
-            <version>2.8.3</version>
         </dependency>
                <dependency>
                        <groupId>org.openrdf.sesame</groupId>
```

**Comment by AEisenkolb** [comment]
@papadako : 

We merged v2-dev to dev, sorry for that! 

I checked the pom and added the dependency to the parent pom, so the explicit versioning is no longer necessary (see e825767f06c20b50278f28e8f326380d6a7b44ed).
