### ISSUE TITLE
"Auto-persistence" of RDF objects

### ISSUE THREAD

**Issue by berndl** [anno4j/anno4j#75]
There is an assumed "auto-persistence" of Alibaba, which occurs when a object is created (but not yet persisted) and then used as a target of a setter. Then Alibaba persists both objects.

If the setter is NOT used, then objects have to be persisted by hand.

(For examples: MatchingVideoSegmentBodyMMMTest does auto-persist, ExtractorMMMSupportTest does not.)

**Comment by schlegel** [comment]
obsolete with newest version
