### ISSUE TITLE
String comparison via QueryService criteria - "contains" as intended behaviour?

### ISSUE THREAD

**Issue by berndl** [anno4j/anno4j#85]
When comparing a String field of a given RDF class via comparison in an QueryService criteria, the test does a "contains"-like query instead of a full match of the String.

E.g. querying for a comparison to "test" on a set of "testbla" and "blatest2" returns both.

If both behaviours are desired, one should be able to specify a "full-match" option.

Exemplary query criteria:
qs.addCriteria("oa:hasBody[is-a <" + TestBody1.URI + ">]/rdf:value", "test", Comparison.EQ)

**Comment by AEisenkolb** [comment]
Hey @berndl:

I introduced new comparison types : StartsWith, EndsWith and Contains. EQ should now work as expected. see @4c4a0dfb38fe835a83c6cebb4c4bad4577c5efa7
